### PR TITLE
Enhance task_output_view and workflow

### PR DESCRIPTION
**Pull request by Pippo8291**
Added some minor tweaks to the formatting of the logs and to the pipeline. Would be fine for me to revert the changes for the pipeline. The modifications to the task_output_view improves readability of the log files. Maybe the colors can be adapted for light mode, but in general this improves the readability a lot (using dark mode, so i'm not sure about that):

* enhance task output view by colors and scroll instead of linebreaks
* pushing artifacts to action summary

### CODE REVIEW

**Comment by Pippo8291** [comment]
@gsmlg Could you review this? Or what is the process for possible changes? ;)

**Comment by gsmlg** [comment]
Thiis pr change whole line color. if a line has multi color or just some keyword is colored, will not be expected.
like this
image

**Comment by gsmlg** [comment]
lgtm

**Comment by Pippo8291** [comment]
Oh Thanks. I tested it with my usecase and it looked good to me too.  Maybe there can be some max line length in the future, but at least my logs are much more readable now.

**Pull request merged**
